#!/bin/bash
echo 'Enter the files to add'
read files
git add $files

echo 'Enter the commit message.'
read commitMessage

git commit -m "$commitMessage"

echo 'Enter the branch name'
read branch
git push origin $branch
exit
